services:
  pdf:
    image: ghcr.io/alam00000/bentopdf:2.1.0@sha256:1be1c12c7c222f9ea01bf7bfc849ebb96e48d4da112f45ef1bab7ef47563a744
    container_name: pdf
    restart: always
    environment:
      TZ: Europe/Berlin
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/bentopdf.webp
      - traefik.enable=true
      - traefik.http.routers.pdf.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.pdf.entrypoints=https
      - traefik.http.routers.pdf.tls=true
      - traefik.http.routers.pdf.tls.certresolver=desec
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
