services:
  pdf:
    image: ghcr.io/alam00000/bentopdf:2.2.1@sha256:b123f74921c079fb2be8a5a04eb576ab542d4a551bc26b291173580b7d037968
    container_name: pdf
    restart: always
    environment:
      TZ: Europe/Berlin
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/bentopdf.webp
      - traefik.enable=true
      - traefik.http.routers.pdf.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.pdf.entrypoints=https
      - traefik.http.routers.pdf.tls=true
      - traefik.http.routers.pdf.tls.certresolver=desec
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
